---
name: CI Copr Post
permissions:
  contents: read

on:
  workflow_run:
    workflows:
      - "CI Copr Call"
    types:
      - completed

jobs:
  # TODO: cancel or download based on the workflow_run conclusion
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
  github-env:
    name: GitHub Env Debug
    uses: LizardByte/.github/.github/workflows/__call-github-env.yml@master
